import { Inter } from "next/font/google";
import Footer from "../Components/Footer";
import Navber from "../Components/Navber";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Blog  Next App",
  description: "Generated by create Blog next app",
};

export default function BlogLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navber/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
